version: "3.9"

services:
  master:
    build: master/
    container_name: master
    ports:
      - 8000:8000
    volumes:
      - ./:/master
    restart: on-failure
    command: python /three_microservices/master/master/app.py
  reaper:
    build: reaper/
    container_name: reaper
    ports:
      - 8001:8001
    volumes:
      - ./:/reaper
    restart: on-failure
    command: python /three_microservices/reaper/reaper/app.py
  keeper:
    build: keeper/
    networks:
      - my-network
    container_name: keeper
    ports:
      - 8002:8002
    volumes:
      - ./:/keeper
    restart: on-failure
    command: python /three_microservices/keeper/keeper/app.py
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    command: mongod --port 27018
    container_name: mongo
    restart: always
    networks:
      - my-network
    ports:
      - 27018:27018

networks:
  my-network:
    driver: bridge
